### PR TITLE
Closes issue #407

### PR DESCRIPTION
**Pull request by rolfvandervleuten**
magnification calculated by instrument / eyepiece / lens or fixed magnificaiton

### CODE REVIEW

**Comment by WimDeMeester** [comment]
Hi Rolf,

Thanks a lot! I still see a few possible improvements:
+ When I select my Telescope with a focal length of 2057mm and a 13mm eyepice, I see a magnification of 158.261538461538x. Can you limit this to 158x (or 158.3x)?
+ When I select an existing magnification and click 'Adapt observation', the magnification is not filled in (I had both a telescope and an eyepiece selected). Can you fix this?

Thanks!

Wim

**Comment by rolfvandervleuten** [comment]
I can't find the second part of your comment, what is the action being performed? I can't seem to find a 'Adapt observation' button

**Comment by WimDeMeester** [comment]
It is the 'Change observation' button at the bottom of the page when you view an observation done by yourself:

issue407


For example: 

http://localhost/index.php?indexAction=detail_observation&observation=81864&QobsKey=0&dalm=D

Change the observationid in the link to an observation of yourself.

**Comment by rolfvandervleuten** [comment]
when I change any of the parameter, the magnification will be calculated. Adding it to the button will result in a change te user really doesn't see. just before closing the magnification will be changed. 
Also what if a user removes the calculated magnification and added his own, the user's input would be overridden when saving. 
Only auto-fill it if the field is empty and button is pushed? downside would be that there is no way to leave the field empty when intended

**Comment by WimDeMeester** [comment]
I see. I just propose to add the rounding of the magnification then.

**Pull request merged**
