### PR TITLE
Datatables 2

### PR DESCRIPTION
**Pull request by rolfvandervleuten**
observations list in datatables

### CODE REVIEW

**Comment by WimDeMeester** [comment]
Hi Rolf,

I looked into the datatables. The result is really amazing. We see an enormous speed improvement in DeepskyLog. However, I still have some remarks:
+ In DeepskyLog 5.0.15, I changed the sorting on the instruments to sort on the diameter, not on the name of the instrument. Can you implement this again in the datatables?
+ Is it correct that only the results of the quickpick will use the new datatables? When I click on 'Search observation', without an object entered, I go (as expected) to the form to search for observations. If I want to get all my observations, I select my name in the drop down. Searching for observations then will use the old tables.
+ It is not longer possible to export the tables. In the previous versions, it was possible using the following buttons:
export

+ The 'Compact', 'Compare' and 'Highlight own observations' buttons are also removed.

Thanks!

**Comment by rolfvandervleuten** [comment]
I totally missed the export buttons. will work on that.
I only linked this view from the quickpick menu, the other pages linking to the view may have some extra variables which I did not sort yet
The compare to others seems useless when you are able to open all observations simultaneously.
The compare to my observation was technically somewhat more comlpex. Takes some extra work.

I thought maybe this first version might already be better than the one live now, considering basic functionality like paging is not working properly. 
And then add more functionality during the next couple of weeks.

**Comment by WimDeMeester** [comment]
I think we will need at least the sorting on instrument diameter and the export buttons. For the rest, I totally agree with you. It is better to release this version after these two things are fixed.

**Comment by WimDeMeester** [comment]
I will not be able to merge this pull request, but you can do this. The online version will be updated automatically during the next night. Don't forget to update the version number in lib/setup/vars.php. Also write a little text in the What's New Page: https://github.com/DeepskyLog/DeepskyLog/wiki/What's-New-in-DeepskyLog

**Pull request merged**
